### ISSUE TITLE
It doesn't work well on iPhone 5

### ISSUE THREAD

**Issue by whitebunny22** [codesinghanoop/react-native-d3multiline-chart#1]
I've developed an analytic app and I need chart. MultiLineChart works well on iPhone 6. But it doesn't work well on iPhone 5. How can I make it responsive to various device?

**Comment by codesinghanoop** [comment]
@whitebunny22  did you find the solution to it ?

**Comment by whitebunny22** [comment]
Yeah, I’ve found it.
Using chartHeight, chartWidth props, I’ve fixed it.
Your package is so good.
