### ISSUE TITLE
How to show values on graph

### ISSUE THREAD

**Issue by rsimbu89** [codesinghanoop/react-native-d3multiline-chart#10]
Hi, 
 I want to show the values on each points([like this](https://github.com/codesinghanoop/react-native-d3multiline-chart/blob/master/Images/example.png)), How can i achieve this, Currently my graph is like below. Need to show the value of each correlation points.
![simulator screen shot - iphone x - 2019-01-06 at 13 41 43](https://user-images.githubusercontent.com/6513047/50733722-d6fbed80-11b8-11e9-8335-c27d5f9215f9.png)

**Comment by codesinghanoop** [comment]
use
pointDataToShowOnGraph

**Comment by rsimbu89** [comment]
Do i need to pass as array or just string?

for example like below ? 
I just did like below, data is not showing.
 let chartDataToShowOnGraph = [1,2,3,4,5,6];

**pointDataToShowOnGraph={chartDataToShowOnGraph}**

**Comment by codesinghanoop** [comment]
Please have a look at the example app.

**Comment by rsimbu89** [comment]
Sorry i could not find the example for it,  in the provided example app its like below only,
pointDataToShowOnGraph=""

Can you please add the link here for reference.

**Comment by codesinghanoop** [comment]
You have to use an array for that.

**Comment by rsimbu89** [comment]
Hi, 
Added the array data below , But data is not showing in graph.

```
let chartTempDataToShowOnGraph = ["28","28","28","28","29","28","29","29","29","29","29","30","30","29","29","29","28","29","30","31","33","34","35","37"];

<MultiLineChart
              data={chartTempDataValues}
              pointDataToShowOnGraph={chartTempDataToShowOnGraph}
              showLegends={false}
              minX={minX}
              maxX={maxX}
              minY={minY}
              maxY={maxY}
              scatterPlotEnable={false}
              dataPointsVisible={true}
              Color={TempColor}
              fillArea={false}
              yAxisGrid={false}
              xAxisGrid={false}
              hideXAxis={true}
              hideYAxis={true}
              inclindTick={false}
              animation={false}
              GraphHeight={120}
              GraphWidth={deviceWidth * 5}
              chartWidth={(deviceWidth * 5) - 20}
              chartHeight={120}
              staggerLength={1}
            />

```

**Comment by rsimbu89** [comment]
Can you guide me to add the pointDataToShowOnGraph?

**Comment by codesinghanoop** [comment]
Right now i’m at office see you tonight at 10pm

**Comment by rsimbu89** [comment]
Ok, Thanks, I can see the data points for Android and iOS (when i removed the pointDataToShowOnGraph={chartTempDataToShowOnGraph},
![871435931554138391](https://user-images.githubusercontent.com/6513047/50883215-6f8aab80-140d-11e9-9996-4f0645d82ba2.png)
