### ISSUE TITLE
TypeError:method.bind is not a function

### ISSUE THREAD

**Issue by erickbank** [codesinghanoop/react-native-d3multiline-chart#14]
after update to RN 0.60 , the package from react-native-svg needs to be updated to latest version , can you update it in package.json? , or there is any fix available?

**Comment by oakcreations** [comment]
@codesinghanoop check my pull request for this issue.
and updated npm install

thx bro

**Comment by codesinghanoop** [comment]
@erickbank  i suppose your issue is resolved by @oakcreations PR. @oakcreations will review your PR and add latest react native version example. Thanks guys

**Comment by erickbank** [comment]
@codesinghanoop pls review @oakcreations PR.

**Comment by codesinghanoop** [comment]
Busy with some other stuff so forgot it to merge. Will review and merge it by tomorrow

**Comment by codesinghanoop** [comment]
@erickbank reviewed and merged
