### ISSUE TITLE
Unable to resolve module `color` from `node_modules/react-native-d3multiline-chart/utils/AnimatedSVGBrush/index.js`: color could not be found within the project.

### ISSUE THREAD

**Issue by Rananjaya** [codesinghanoop/react-native-d3multiline-chart#16]
Unable to resolve module `color` from `node_modules/react-native-d3multiline-chart/utils/AnimatedSVGBrush/index.js`: color could not be found within the project.

**Comment by codesinghanoop** [comment]
@Rananjaya please share the code in which you are facing this issue

**Comment by codesinghanoop** [comment]
@Rananjaya Due to inactivity i'm closing this issue. Feel free to reopen if it's not resolved
