### ISSUE TITLE
Requires install of svg-path-properties which is not included in Readme, by default?

### ISSUE THREAD

**Issue by amcabrj** [codesinghanoop/react-native-d3multiline-chart#19]
Thanks for creating this library! I installed it as per Read me, however, it would still ask me install missing dependency of svg-path-properties and after adding svg-path-properties 1.0.2 version library getting another issue 'e not found in t' 't is not an object'. 
was trying to run below code which is from one your samples. 

Any small help would be a great favor!!

   `import React, {Component} from 'react';
    import {StyleSheet, View, TouchableOpacity, Dimensions} from 'react-native';
    import * as d3 from 'd3';
    import * as scale from 'd3-scale';
    import _ from 'lodash'; 
    import {MultiLineChart} from 'react-native-d3multiline-chart';

const deviceWidth = Dimensions.get ('window').width;
const deviceHeight = Dimensions.get ('window').height;

var data = [
  [
    {
      y: '202',
      x: 2000,
    },
    {
      y: '215',
      x: 2001,
    },
    {
      y: '179',
      x: 2002,
    },
    {
      y: '199',
      x: 2003,
    },
    {
      y: '134',
      x: 2003,
    },
    {
      y: '176',
      x: 2010,
    },
  ],
  [
    {
      y: '152',
      x: 2000,
    },
    {
      y: '189',
      x: 2002,
    },
    {
      y: '179',
      x: 2004,
    },
    {
      y: '199',
      x: 2006,
    },
    {
      y: '134',
      x: 2008,
    },
    {
      y: '176',
      x: 2010,
    },
  ],
  [
    {
      y: '200',
      x: 2000,
    },
    {
      y: '200',
      x: 2001,
    },
    {
      y: '200',
      x: 2002,
    },
    {
      y: '200',
      x: 2003,
    },
    {
      y: '134',
      x: 2003,
    },
    {
      y: '176',
      x: 2010,
    },
  ],
];

let leftAxisData = [134, 144, 154, 164, 174, 184, 194, 204, 215];
let bottomAxisData = [2000, 2002, 2004, 2006, 2008, 2010];
let legendColor = ['#00b7d4', 'red', 'black'];
let legendText = ['sales', 'year', 'profit'];
let minX = 2000, maxX = 2010;
let minY = 134, maxY = 215;

//since there are only two lines
var Color = ['#00b7d4', 'red', 'black'];
//general data to represent ticks in y-axis and it doesn't take part in calculation
let bottomAxisDataToShow = [
  'Jan 2017',
  'Feb 2017',
  'Mar 2017',
  'Apr 2017',
  'May 2017',
  'Jun 2017',
  'Jul 2017',
  'Aug 2017',
];
//general data to represent ticks in y-axis and it doesn't take part in calculation
let leftAxisDataToShow = [
  '10%',
  '20%',
  '30%',
  '40%',
  '50%',
  '60%',
  '70%',
  '80%',
  '90%',
];
export default class MultiChart extends Component {
  constructor (props) {
    super (props);
    this.state = {
      data: data,
    };
  }
  render () {
    const {data} = this.state;
    return (
       
      <View style={styles.container}>
        <MultiLineChart
          data={data}
          leftAxisData={leftAxisData}
          bottomAxisData={bottomAxisData}
          legendColor={legendColor}
          legendText={legendText}
          minX={minX}
          maxX={maxX}
          minY={minY}
          maxY={maxY}
          scatterPlotEnable={false}
          dataPointsVisible={true}
          Color={Color}
          bottomAxisDataToShow={bottomAxisDataToShow}
          circleLegendType={true}
          fillArea={true}
          yAxisGrid={false}
          xAxisGrid={false}
          hideXAxis={false}
          hideYAxis={false}
          inclindTick={false}
          pointDataToShowOnGraph=""
          animation={true}
          duration={1500}
          delay={1000}
          GraphHeight={300}
          GraphWidth={deviceWidth}
          chartWidth={deviceWidth - 20}
          chartHeight={250}
          staggerLength={220}
          speed={50}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create ({
  container: {
    flex: 1,
    justifyContent: 'center',
  },
});`

Attaching below screenshot, one before adding svg-path-properties.

![Screenshot_1578321287](https://user-images.githubusercontent.com/57209358/71824607-f5444400-30bf-11ea-812d-17e67a3a0f81.png)

**Comment by codesinghanoop** [comment]
@amcabrj thanks for using this package. My first question is there any other version of react-native-svg in your project ?

**Comment by codesinghanoop** [comment]
@amcabrj Due to inactivity closing this issue..feel free to open if this still exist
