### ISSUE TITLE
Unable to resolve module `svg-path-properties`

### ISSUE THREAD

**Issue by i-suraj** [codesinghanoop/react-native-d3multiline-chart#3]
I got this error while running this package.

Unable to resolve module `svg-path-properties` from `Desktop/mygraph/node_modules/react-native-d3multiline-chart/multipleLineChart.js`: Module does not exist in the module map

**Comment by codesinghanoop** [comment]
@suraj-epsumlabs i think you have 2 versions of react-native-svg install in your project. Please install the one which is in the dependency of this module.

**Comment by codesinghanoop** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help 👍

**Comment by JTavares95** [comment]
+1

**Comment by codesinghanoop** [comment]
@JTavares95 what is the version of react-native-svg and was there any react-native-svg version already available in your project ?

**Comment by JTavares95** [comment]
this is my dependencies list
`"dependencies": {
    "moment": "^2.20.1",
    "react": "16.2.0",
    "react-native": "0.53.0",
    "react-native-config": "^0.11.5",
    "react-native-d3multiline-chart": "^1.0.18",
    "react-native-datepicker-dialog": "^0.0.9",
    "react-native-elements": "^0.19.0",
    "react-native-modal-picker": "^0.0.16",
    "react-native-multiple-select": "^0.4.1",
    "react-native-svg": "^6.3.1",
    "react-native-svg-charts": "^4.2.0",
    "react-native-switch-selector": "^1.1.5",
    "react-native-vector-icons": "^4.5.0",
    "react-navigation": "^1.0.3",
    "react-navigation-redux-helpers": "^1.0.1",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6"
  },`
before i installed this library, i had already react-native-svg

**Comment by codesinghanoop** [comment]
@JTavares95 try react-native-svg: 5.4.1 and let me know if you still face any problem.

**Comment by JTavares95** [comment]
@codesinghanoop  just change the version?

**Comment by codesinghanoop** [comment]
@JTavares95 and run npm install and react-native link.

**Comment by JTavares95** [comment]
@codesinghanoop  problem remains...

**Comment by codesinghanoop** [comment]
@JTavares95 remove react-native-svg folder from the node_modules folder and run react-native unlink react-native-svg from root dir of your project and make a fresh try of integrating react-native-svg version:-  5.4.1

**Comment by codesinghanoop** [comment]
@JTavares95  react-native-svg is the peer dependency of this project. So you have to use 5.4.1 version.

**Comment by codesinghanoop** [comment]
@JTavares95  https://github.com/react-native-community/react-native-svg#notice this will help you understand the version issue.

**Comment by JTavares95** [comment]
@codesinghanoop i can't make this work....
i've installed the 5.4.1 version but it doesn't work

**Comment by codesinghanoop** [comment]
@JTavares95 please show me your package.json

**Comment by JTavares95** [comment]
@codesinghanoop 
`
{
  "name": "finance_app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "moment": "^2.20.1",
    "react": "16.2.0",
    "react-native": "0.53.0",
    "react-native-config": "^0.11.5",
    "react-native-d3multiline-chart": "^1.0.18",
    "react-native-datepicker-dialog": "^0.0.9",
    "react-native-elements": "^0.19.0",
    "react-native-modal-picker": "^0.0.16",
    "react-native-multiple-select": "^0.4.1",
    "react-native-svg": "5.4.1",
    "react-native-svg-charts": "^4.2.0",
    "react-native-switch-selector": "^1.1.5",
    "react-native-vector-icons": "^4.5.0",
    "react-navigation": "^1.0.3",
    "react-navigation-redux-helpers": "^1.0.1",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6"
  },
  "devDependencies": {
    "babel-jest": "22.2.2",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.2.2",
    "react-test-renderer": "16.2.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./app/assets/fonts/"
    ]
  }
}

`

**Comment by codesinghanoop** [comment]
@JTavares95 change your react version to react == 16.0.0.

**Comment by JTavares95** [comment]
@codesinghanoop 
finally, it's working
i did 'yarn install svg-path-properties'

**Comment by codesinghanoop** [comment]
@JTavares95 sounds good.

**Comment by Ahmad5448** [comment]
I installed but it says type error :t is not an object evaluating (I in t)
what's this bro ???
