### ISSUE TITLE
How To Convert Graph into an BASE64 Image?

### ISSUE THREAD

**Issue by singhlovey** [codesinghanoop/react-native-d3multiline-chart#4]
Hi,

I am able to achieve the requirements of integrating graph in my react native app. It works great. Thanks for this plugin.

Now my requirement is that I want to convert graph into an image so that I can attach that graph into pdf file. can you please help me out and do let me know how can I achieve this?

Thanks 

Lovedeep

**Comment by codesinghanoop** [comment]
@singhlovey Hi, thanks for using this package. Currently, there isn't any feature as such however, lib is open for PR and will look into this if i can help you.

**Comment by codesinghanoop** [comment]
This is inactive for a while so closing it. LMK if you need my help.

**Comment by singhlovey** [comment]
Hi,

This is done.

Thanks

**Comment by codesinghanoop** [comment]
hey @singhlovey would you like to share how you implement this?
