### ISSUE TITLE
Can I draw a chart like this??

### ISSUE THREAD

**Issue by MohithHasan** [codesinghanoop/react-native-d3multiline-chart#5]
![scatter](https://user-images.githubusercontent.com/34531234/39812208-8eca1268-53ad-11e8-8982-1c1086cd9508.PNG)

**Comment by codesinghanoop** [comment]
@MohithHasan Yes, you can set the coordinates according to your need and the chart would appear to be like above. Apparently, In the above chart x-coord is constant for all lines however, y-coord is variable.  Let me know if you need any kind of help.

**Comment by codesinghanoop** [comment]
This is inactive for a while so closing it. LMK if you need my help.
