### ISSUE TITLE
App getting crash on IOS

### ISSUE THREAD

**Issue by akamahesh** [codesinghanoop/react-native-d3multiline-chart#8]
I getting this crash on ios , 
I am using minimal code from you example app.js 
this is my package.json 

```
"dependencies": {
    "@babel/runtime": "^7.1.2",
    "lodash": "^4.17.11",
    "moment": "^2.22.2",
    "react": "16.5.0",
    "react-native": "0.57.1",
    "react-native-d3multiline-chart": "1.0.18",
    "react-native-linear-gradient": "^2.4.2",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-multiple-picker": "0.0.21",
    "react-native-splash-screen": "^3.1.1",
    "react-native-svg": "^8.0.3",
    "react-native-svg-animations": "0.1.5",
    "react-native-table-component": "^1.1.8",
    "react-navigation": "^2.17.0",
    "svg-path-properties": "0.4.1"
  },

```
IOS xcode log 

2018-11-01 16:29:51.146 [error][tid:main][RCTComponentData.m:253] No +[RCTConvert RNSVGTextAnchor:] function found.
2018-11-01 16:29:51.145947+0530 DBReport[24020:283224] No +[RCTConvert RNSVGTextAnchor:] function found.
2018-11-01 16:29:51.150 [error][tid:main][RCTComponentData.m:253] No +[RCTConvert RNSVGTextAnchor:] function found.
2018-11-01 16:29:51.150495+0530 DBReport[24020:283224] No +[RCTConvert RNSVGTextAnchor:] function found.
2018-11-01 16:29:51.205678+0530 DBReport[24020:283224] -[__NSCFNumber stringByTrimmingCharactersInSet:]: unrecognized selector sent to instance 0xb0000000000000a3
2018-11-01 16:29:51.209316+0530 DBReport[24020:283224] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber stringByTrimmingCharactersInSet:]: unrecognized selector sent to instance 0xb0000000000000a3'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000106d761e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x0000000105662031 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000106df7784 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000106cf8898 ___forwarding___ + 1432
	4   CoreFoundation                      0x0000000106cf8278 _CF_forwarding_prep_0 + 120
	5   DBReport                            0x0000000104857ec3 +[RNSVGPropHelper fromRelativeWithNSString:relative:fontSize:] + 163
	6   DBReport                            0x0000000104860500 +[RNSVGFontData initWithNSDictionary:parent:] + 272
	7   DBReport                            0x000000010484334a -[RNSVGGlyphContext pushNode:andFont:] + 218
	8   DBReport                            0x00000001048435dd -[RNSVGGlyphContext pushContext:font:x:y:deltaX:deltaY:rotate:] + 285
	9   DBReport                            0x0000000104835dc8 -[RNSVGText pushGlyphContext] + 344
	10  DBReport                            0x0000000104835577 -[RNSVGText getGroupPath:] + 39
	11  DBReport                            0x000000010483542d -[RNSVGText renderLayerTo:rect:] + 125
	12  DBReport                            0x0000000104837b31 -[RNSVGRenderable renderTo:rect:] + 2593
	13  DBReport                            0x000000010483a70d __33-[RNSVGGroup renderGroupTo:rect:]_block_invoke + 557
	14  DBReport                            0x0000000104840868 -[RNSVGNode traverseSubviews:] + 360
	15  DBReport                            0x000000010483a2ac -[RNSVGGroup renderGroupTo:rect:] + 348
	16  DBReport                            0x000000010483a14a -[RNSVGGroup renderLayerTo:rect:] + 154
	17  DBReport                            0x0000000104837b31 -[RNSVGRenderable renderTo:rect:] + 2593
	18  DBReport                            0x000000010483a70d __33-[RNSVGGroup renderGroupTo:rect:]_block_invoke + 557
	19  DBReport                            0x0000000104840868 -[RNSVGNode traverseSubviews:] + 360
	20  DBReport                            0x000000010483a2ac -[RNSVGGroup renderGroupTo:rect:] + 348
	21  DBReport                            0x000000010483a14a -[RNSVGGroup renderLayerTo:rect:] + 154
	22  DBReport                            0x0000000104837b31 -[RNSVGRenderable renderTo:rect:] + 2593
	23  DBReport                            0x000000010485e326 -[RNSVGSvgView drawToContext:withRect:] + 1654
	24  DBReport                            0x000000010485e8b8 -[RNSVGSvgView drawRect:] + 1048
	25  UIKit                               0x000000010983ad90 -[UIView(CALayerDelegate) drawLayer:inContext:] + 600
	26  QuartzCore                          0x000000010933207e -[CALayer drawInContext:] + 305
	27  QuartzCore                          0x00000001092407c8 CABackingStoreUpdate_ + 254
	28  QuartzCore                          0x00000001093382a0 ___ZN2CA5Layer8display_Ev_block_invoke + 44
	29  QuartzCore                          0x0000000109331b94 -[CALayer _display] + 2019
	30  QuartzCore                          0x00000001092bd21e _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 634
	31  QuartzCore                          0x00000001092ea79c _ZN2CA11Transaction6commitEv + 568
	32  UIKit                               0x0000000109794f2c _afterCACommitHandler + 272
	33  CoreFoundation                      0x0000000106d18607 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	34  CoreFoundation                      0x0000000106d1855e __CFRunLoopDoObservers + 430
	35  CoreFoundation                      0x0000000106cfcb81 __CFRunLoopRun + 1537
	36  CoreFoundation                      0x0000000106cfc30b CFRunLoopRunSpecific + 635
	37  GraphicsServices                    0x000000010e850a73 GSEventRunModal + 62
	38  UIKit                               0x000000010976c057 UIApplicationMain + 159
	39  DBReport                            0x0000000104546a8f main + 111
	40  libdyld.dylib                       0x000000010c3a6955 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by codesinghanoop** [comment]
@akamahesh what i can see in the above post is you already have integrated react-native-svg in your project and this library also uses it so there is a conflict between the different versions of library. I would suggest you to remove the version of react-native-svg from your project because this library works best with the version that is inside it.

**Comment by nayfusaurus** [comment]
@codesinghanoop Thank you for your work on the library! Would it be possible to update the library to use a newer version of react-native-svg?

**Comment by codesinghanoop** [comment]
Will check and let you know

**Comment by codesinghanoop** [comment]
@nayfusaurus did you find a way to control crash ?

**Comment by nayfusaurus** [comment]
@codesinghanoop , Sorry i havent looked at it for quite sometime.

**Comment by akamahesh** [comment]
> @akamahesh what i can see in the above post is you already have integrated react-native-svg in your project and this library also uses it so there is a conflict between the different versions of library. I would suggest you to remove the version of react-native-svg from your project because this library works best with the version that is inside it.

Sorry i forgot to thank you,
Ur solution worked and saved my ass :)
Thanks man!
