### ISSUE TITLE
 Module `react-native-svg` does not exist

### ISSUE THREAD

**Issue by rsimbu89** [codesinghanoop/react-native-d3multiline-chart#9]
Hi, Getting below error, 

**LineChartView.js`: Module `react-native-svg` does not exist in the Haste module map**

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency

**Comment by codesinghanoop** [comment]
Will help you tonight right now i’m in office

**Comment by rsimbu89** [comment]
I've resolved that, Thanks

**Comment by ghost** [comment]
> I've resolved that, Thanks

how you resolved?

**Comment by hapSa000** [comment]
same problem anyone here to reply

**Comment by codesinghanoop** [comment]
After you have integrated this package you have to build your project again to replicate the changes or there can be a chance that there are two versions of react-native-svg in your app, so to resolve this you can remove the version of react-native-svg integrated in your app not the one integrated with this lib.

**Comment by codesinghanoop** [comment]
@hapSa000 let me know if you face any issue.
